### ISSUE TITLE
Consistently reproducible C++ Runtime error on reloading Electron window: g_coreclr == nullptr

### ISSUE THREAD

**Issue by tjcouch-sil** [agracio/electron-edge-js-quick-start#16] opened 2023-01-18 23:13 UTC
Hello!

It seems I am having a consistent assertion failure on reloading the electron app with this quick start repo.

Steps to reproduce:
1. Clone the repo `git clone https://github.com/agracio/electron-edge-js-quick-start.git`
2. Install NPM dependencies `npm install`
3. Build .NET project `dotnet build src/QuickStart.sln`
4. Run the electron app `npm start`
5. Notice that the calls to C# function perfectly!
6. Reload with Ctrl+R or View->Reload
7. Microsoft Visual C++ Runtime Library window pops up with "Assertion failed! coreclr.cpp Line 49 Expression: g_coreclr == nullptr" as pictured:
![image](https://user-images.githubusercontent.com/104016682/213314554-f5645be7-871d-41ff-a372-5ddb9ebde14a.png)
8. To see what happens, click Ignore
9. Notice that there are no results in the window anymore as pictured:
![image](https://user-images.githubusercontent.com/104016682/213315044-18068f93-4771-4926-8eab-04e6b4ee30b2.png)

I am running in Windows. I have **VS2022** installed. I wonder if this affects anything. I also experience this issue after upgrading to .NET 6 and 7 in `ExternalLibrary` and `QuickStart.Core`.

Do you have any ideas or suggestions for me to try? Or if I should move this to the [edge-js](https://github.com/agracio/edge-js) repo or the [electron-edge-js](https://github.com/agracio/electron-edge-js) repo, let me know. Thank you very much for your time!

Thank you also for your hard work on electron-edge-js. It is quite a unique and powerful solution to bridging Node and .NET.

Update: I installed VS2017 and tried again. When building, I receive an error that says, "The current .NET SDK does not support targeting .NET Core 3.1. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1." I tried enabling [previews of the .NET Core SDK](https://stackoverflow.com/a/53641974/8535752), but that did not remove the error. It seems it may be a limitation of VS2017 because [it does not use MSBuild 16](https://stackoverflow.com/a/56214780/8535752). I also tried changing the .NET Core version to 1.1, fixing the `AppDomain` error, building (successfully!), and running the electron app. I got the same blank tables as in my second screenshot above. Reloading the page yielded the same runtime error as discussed above. I imagine this error is not related to the VS version or the .NET version but to edge-js or some aspect of this quick-start project. Let me know what you think. Thank you!

**Comment by agracio** [comment] 2024-09-18 14:16
Duplicate of https://github.com/agracio/electron-edge-js/issues/89, currently there is no solution for this problem when `electron-edge-js` is used on main Electron thread. The only way to mitigate it is to create Electron app using Electron [IPC](https://www.electronjs.org/docs/latest/tutorial/ipc).
'quick-start' is already updated and no longer has that issue.

**Closed as completed by agracio** 2024-09-18 14:16 UTC

**Comment by hellozyemlya** [comment] 2024-10-22 21:33
@agracio "main thread" is a thread where browser javascript executed, e.g. render process?

**Comment by agracio** [comment] 2024-10-22 21:41
Yes, updated quick-start uses Electron IPC model to mitigate the problem.
